[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lamports_vault = "9PixWTTq2tjkhpvVMeYbdYaztEsuCA4aS9d43AUnYC7A"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
